---
kind: Service
apiVersion: v1
metadata:
  name: sgx-svc
  labels:
    app: custom-nginx
spec:
  selector:
    app: custom-nginx
  type: NodePort
  ports:
    - name: https
      port: 8080
      targetPort: 2443
      nodePort: 30443
      protocol: TCP
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30480
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgx-deployment
  labels:
    name: custom-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
        - name: custom-nginx
          image: isecl/sgx:latest
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 8080
           - containerPort: 2443
          volumeMounts:
           - mountPath: /var/log/nginx
             name: nginx-log-volume
           - mountPath: /skc_library.conf
             name: skclib-config-volume
           - mountPath: /etc/nginx/nginx.conf
             name: nginx-config-volume
           - mountPath: /root/keys.txt
             name: kms-key-volume
           - mountPath: /etc/sgx_default_qcnl.conf
             name: sgx-conf-volume
           - mountPath: /etc/pki/tls/openssl.cnf
             name: openssl-config-volume
           - mountPath: /opt/skc/etc/pkcs11-apimodule.ini
             name: pkcs11-config-volume
           - mountPath: /root/e030eaab-1207-44e4-b7a5-a7a3707f98b5.crt
             name: kms-cert-volume
           - mountPath: /etc/hosts
             name: haproxy-hosts
          securityContext:
             privileged: true
      volumes:
        - hostPath:
             path: /var/log/nginx
          name: nginx-log-volume
        - hostPath:
             path: /root/vartika/docker-stuff/skc_library.conf
             type: FileOrCreate
          name: skclib-config-volume
        - hostPath:
             path: /root/vartika/docker-stuff/nginx.conf
             type: FileOrCreate
          name: nginx-config-volume
        - hostPath:
             path: /root/vartika/docker-stuff/keys.txt
             type: FileOrCreate
          name: kms-key-volume
        - hostPath:
             path: /root/vartika/docker-stuff/sgx_default_qcnl.conf
             type: FileOrCreate
          name: sgx-conf-volume
        - hostPath:
             path: /root/vartika/docker-stuff/openssl.cnf
             type: FileOrCreate
          name: openssl-config-volume
        - hostPath: 
             path: /root/vartika/docker-stuff/pkcs11-apimodule.ini
             type: FileOrCreate
          name: pkcs11-config-volume
        - hostPath:
             path: /root/vartika/docker-stuff/e030eaab-1207-44e4-b7a5-a7a3707f98b5.crt
             type: FileOrCreate
          name: kms-cert-volume
        - hostPath:
             path: /root/vartika/docker-stuff/hosts
             type: FileOrCreate
          name: haproxy-hosts
